Repository wecode-bootcamp-korea/27-1st-Brokurly-backend, pull requests merged in 2021-12, with the labels that each got.

#1 [Add] model-created
  .gitignore
  brokurly/settings.py
  cart/__init__.py
  cart/admin.py
  cart/apps.py
  cart/migrations/0001_initial.py
  cart/migrations/__init__.py
  cart/models.py
  cart/tests.py
  cart/views.py
  core/__init__.py
  core/admin.py
  core/apps.py
  core/migrations/__init__.py
  core/models.py
  core/tests.py
  core/views.py
  orders/__init__.py
  orders/admin.py
  orders/apps.py
  orders/migrations/0001_initial.py
  orders/migrations/__init__.py
  orders/models.py
  orders/tests.py
  orders/views.py
  products/__init__.py
  products/admin.py
  products/apps.py
  products/migrations/0001_initial.py
  products/migrations/__init__.py
  products/models.py
  products/tests.py
  products/views.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/0001_initial.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/views.py
Labels: Status: 리뷰 요청

#2 Feature/cart modified
  cart/migrations/0002_alter_cart_table.py
  cart/models.py
  requirements.txt
Labels: Status: Accepted

#3 Feature/models modified
  products/migrations/0002_image.py
  products/models.py
Labels: Status: 리뷰 요청

#4 product-model-modified
  products/migrations/0003_auto_20211203_0108.py
  products/models.py
Labels: Status: 리뷰 요청

#7 [add]users-models-contact
  cart/migrations/0001_initial.py
  cart/migrations/0002_alter_cart_table.py
  orders/migrations/0001_initial.py
  products/migrations/0001_initial.py
  products/migrations/0002_image.py
  products/migrations/0003_auto_20211203_0108.py
  users/migrations/0001_initial.py
  users/models.py
Labels: Status: Rebase 요청

#10 [modify]model-modified
  users/models.py
Labels: Status: 리뷰 요청

#8 [Add] core - validator.py 추가
  .gitignore
  cart/migrations/0001_initial.py
  core/validator.py
  orders/migrations/0001_initial.py
  products/migrations/0001_initial.py
  users/migrations/0001_initial.py
Labels: Status: 리뷰 요청

#12 [ADD] : 회원가입 기능 추가
  brokurly/urls.py
  requirements.txt
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#13 [Modify]modified REGEX_PASSWORD, CONTACT
  core/validator.py
Labels: Status: Accepted

#14 [modify]models
  users/models.py
Labels: Status: Accepted

#15 [modify]models
  users/migrations/0002_alter_user_contact.py
Labels: Status: Accepted

#16 [ADD]: 로그인 기능 구현 및 validator.py 연동
  brokurly/settings.py
  core/validator.py
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#6 [성종호][modify]product_detail_view
  brokurly/urls.py
  orders/urls.py
  orders/views.py
  products/urls.py
  products/views.py
Labels: Status: 리뷰 요청

#11 [Create] created decorator.py
  brokurly/urls.py
  core/decorator.py
Labels: Status: 리뷰 요청

#17 [Modify]: check_existing_수정 및 contact 유효성검사삭제
  .gitignore
  cart/urls.py
  cart/views.py
  core/validator.py
  products/models.py
  requirements.txt
  users/views.py
Labels: Status: Accepted

#18 [Modify]Decorator error 추가 및 코드 수정
  core/decorator.py
Labels: Status: Accepted

#9 [add]jongho-order
  brokurly/urls.py
  cart/migrations/0001_initial.py
  orders/migrations/0001_initial.py
  orders/models.py
  orders/urls.py
  orders/views.py
  products/migrations/0001_initial.py
  users/migrations/0001_initial.py
Labels: Status: 리뷰 요청

#20 Feature/seyong cartview
  brokurly/urls.py
  cart/urls.py
  cart/views.py
  products/views.py
  users/views.py
Labels: Status: 리뷰 요청

#19 [Create] 메인페이지 ProductView 클래스 구현
  products/urls.py
  products/views.py
Labels: Status: 리뷰 요청

#21 Feature/models modified
  products/models.py
Labels: Status: 리뷰 요청

#22 [modify]signin-view
  products/migrations/0002_alter_product_weight.py
  users/views.py
Labels: Status: 리뷰 요청

#23 [Feature/fix branch] decorator, cart views codes modified
  cart/migrations/0001_initial.py
  cart/views.py
  core/decorator.py
  orders/migrations/0001_initial.py
  products/migrations/0001_initial.py
  products/views.py
  users/migrations/0001_initial.py
  users/migrations/0002_alter_user_contact.py
  users/views.py
Labels: Status: 리뷰 요청
